# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse202")

model.instance <- InlineResponse202$new()

test_that("task_id", {
  # tests for the property `task_id` (character)
  # ID for the task responsible for managing the copy.

  # uncomment below to test the property 
  #expect_equal(model.instance$`task_id`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of file creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

