# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilesGetResponse")

model.instance <- FilesGetResponse$new()

test_that("files", {
  # tests for the property `files` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

