# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject1")

model.instance <- InlineObject1$new()

test_that("reason", {
  # tests for the property `reason` (character)
  # User-friendly reason for the bundle or timestamp-specfic bundle deletion.

  # uncomment below to test the property 
  #expect_equal(model.instance$`reason`, "EXPECTED_RESULT")
})

