# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject7")

model.instance <- InlineObject7$new()

test_that("attachments", {
  # tests for the property `attachments` (map(SubscriptionsAttachments))
  # The set of bundle metadata items to be included in the payload of a notification request to a subscription endpoint. Each property in this object represents an attachment to the notification payload. Each attachment will be a child property of the &#x60;attachments&#x60; property of the payload. The name of such a child property can be chosen freely provided it does not start with an underscore. For example, if the subscription is &#x60;&#x60;&#x60; {   \&quot;attachments\&quot;: {     \&quot;taxon\&quot;: {       \&quot;type\&quot;: \&quot;jmespath\&quot;,       \&quot;expression\&quot;: \&quot;files.biomaterial_json.biomaterials[].content.biomaterial_core.ncbi_taxon_id[]\&quot;     }   } } &#x60;&#x60;&#x60; the corresponding notification payload will contain the following entry &#x60;&#x60;&#x60; \&quot;attachments\&quot;: {   \&quot;taxon\&quot;: [9606, 9606] } &#x60;&#x60;&#x60; If a general error occurs during the processing of attachments, the notification will be sent with &#x60;attachments&#x60; containing only the reserved &#x60;_errors&#x60; attachment containing a string describing the error. If an error occurs during the processing of a specific attachment, the notification will be sent with all successfully processed attachments and additionally the &#x60;_errors&#x60; attachment containing an object with one property for each failed attachment. For example, &#x60;&#x60;&#x60; \&quot;attachments\&quot;: {   \&quot;taxon\&quot;: [9606, 9606]   \&quot;_errors\&quot; {     \&quot;biomaterial\&quot;: \&quot;Some error occurred\&quot;   } } &#x60;&#x60;&#x60; The value of the &#x60;attachments&#x60; property must be less than or equal to 128 KiB in size when serialized to JSON and encoded as UTF-8. If it is not, the notification will be sent with \&quot;attachments\&quot;: {   \&quot;_errors\&quot;: \&quot;Attachments too large (131073 bytes)\&quot; } 

  # uncomment below to test the property 
  #expect_equal(model.instance$`attachments`, "EXPECTED_RESULT")
})

test_that("callback_url", {
  # tests for the property `callback_url` (character)
  # The subscriber&#39;s URL. An HTTP request is made to the specified URL for every attempt to deliver a notification to the subscriber. If the HTTP response code is 2XX, the delivery attempt is considered successful. Otherwise, more attempts will be made with an exponentially increasing delay between attempts, until an attempt is successful or the a maximum number of attempts is reached. Occasionally, duplicate notifications may be sent. It is up to the receiver of the notification to tolerate duplicate notifications. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`callback_url`, "EXPECTED_RESULT")
})

test_that("encoding", {
  # tests for the property `encoding` (character)
  # The MIME type describing the encoding of the request body * &#x60;application/json&#x60; - the HTTP request body is the notification payload as JSON * &#x60;multipart/form-data&#x60; - the HTTP request body is a list of form fields, each consisting of a name   and a corresponding value. See https://tools.ietf.org/html/rfc7578 for details on this encoding.   The actual notification payload will be placed as JSON into a field of the name specified via   &#x60;payload_form_field&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`encoding`, "EXPECTED_RESULT")
})

test_that("es_query", {
  # tests for the property `es_query` (object)
  # An Elasticsearch query for restricting the set of bundles for which the subscriber is notified. The subscriber will only be notified for newly indexed bundles that match the given query. If this parameter is present the subscription will be of type &#x60;elasticsearch&#x60;, otherwise it will be of type &#x60;jmespath&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`es_query`, "EXPECTED_RESULT")
})

test_that("form_fields", {
  # tests for the property `form_fields` (map(character))
  # A collection of static form fields to be supplied in the request body, alongside the actual notification payload. The value of each field must be a string. For example, if the subscriptions has this property set to &#x60;{\&quot;foo\&quot; : \&quot;bar\&quot;}&#x60;, the corresponding notification HTTP request body will be &#x60;&#x60;&#x60; --2769baffc4f24cbc83ced26aa0c2f712 Content-Disposition: form-data; name&#x3D;\&quot;foo\&quot; bar Content-Disposition: form-data; name&#x3D;\&quot;payload\&quot; {\&quot;transaction_id\&quot;: \&quot;301c9079-3b20-4311-a131-bcda9b7f08ba\&quot;, \&quot;subscription_id\&quot;: ... --2769baffc4f24cbc83ced26aa0c2f712-- &#x60;&#x60;&#x60; Since the type of this property is &#x60;object&#x60;, multi-valued fields are not supported. This property is ignored unless &#x60;encoding&#x60; is &#x60;multipart/form-data&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`form_fields`, "EXPECTED_RESULT")
})

test_that("hmac_key_id", {
  # tests for the property `hmac_key_id` (character)
  # An optional key ID to use with &#x60;hmac_secret_key&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`hmac_key_id`, "EXPECTED_RESULT")
})

test_that("hmac_secret_key", {
  # tests for the property `hmac_secret_key` (character)
  # The key for signing requests to the subscriber&#39;s URL. The signature will be constructed according to https://tools.ietf.org/html/draft-cavage-http-signatures and transmitted in the HTTP &#x60;Authorization&#x60; header. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`hmac_secret_key`, "EXPECTED_RESULT")
})

test_that("jmespath_query", {
  # tests for the property `jmespath_query` (character)
  # An JMESPath query for restricting the set of bundles for which the subscriber is notified. The subscriber will only be notified for new bundles that match the given query. If &#x60;es_query&#x60; is specified, the subscription will be of type &#x60;elasticsearch&#x60;. If &#x60;es_query&#x60; is not present, the subscription will be of type &#x60;jmespath&#x60; 

  # uncomment below to test the property 
  #expect_equal(model.instance$`jmespath_query`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (character)
  # The HTTP request method to use when delivering a notification to the subscriber.

  # uncomment below to test the property 
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("payload_form_field", {
  # tests for the property `payload_form_field` (character)
  # The name of the form field that will hold the notification payload when the request is made. If the default name of the payload field collides with that of a field in &#x60;form_fields&#x60;, this porperty can be used to rename the payload and avoid the collision. This property is ignored unless &#x60;encoding&#x60; is &#x60;multipart/form-data&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`payload_form_field`, "EXPECTED_RESULT")
})

