# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Error")

model.instance <- Error$new()

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly.  Individual endpoints should list an enumeration of possible return codes.  All endpoints should expect the possibility of the return code &#x60;unhandled_exception&#x60; and &#x60;illegal_arguments&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("stacktrace", {
  # tests for the property `stacktrace` (character)
  # Exception stacktrace, if any.

  # uncomment below to test the property 
  #expect_equal(model.instance$`stacktrace`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)
  # HTTP error code.

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # Human-readable error code.

  # uncomment below to test the property 
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

