# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FileVersion")

model.instance <- FileVersion$new()

test_that("content-type", {
  # tests for the property `content-type` (character)
  # Content-type of the file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`content-type`, "EXPECTED_RESULT")
})

test_that("crc32c", {
  # tests for the property `crc32c` (character)
  # CRC-32C (in hex format) of the file contents in hex.

  # uncomment below to test the property 
  #expect_equal(model.instance$`crc32c`, "EXPECTED_RESULT")
})

test_that("indexed", {
  # tests for the property `indexed` (character)
  # True if this file is to be indexed.

  # uncomment below to test the property 
  #expect_equal(model.instance$`indexed`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Filename (unique within a bundle)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("s3_etag", {
  # tests for the property `s3_etag` (character)
  # S3 ETag (in hex format) of the file contents.

  # uncomment below to test the property 
  #expect_equal(model.instance$`s3_etag`, "EXPECTED_RESULT")
})

test_that("sha1", {
  # tests for the property `sha1` (character)
  # SHA-1 (in hex format) of the file contents in hex.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sha1`, "EXPECTED_RESULT")
})

test_that("sha256", {
  # tests for the property `sha256` (character)
  # SHA-256 (in hex format) of the file contents in hex.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sha256`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)
  # File size (bytes).

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # Direct access or presigned URL, if requested.

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A RFC4122-compliant ID for the file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of bundle creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

