# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2003")

model.instance <- InlineResponse2003$new()

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A RFC4122-compliant ID of this bundle.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # New version of the updated bundle.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

