# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject4")

model.instance <- InlineObject4$new()

test_that("add_contents", {
  # tests for the property `add_contents` (array[CollectionItem])
  # List of new items to add to the collection. Items are de-duplicated (if an identical item is already present in the collection or given multiple times, it will only be added once). 

  # uncomment below to test the property 
  #expect_equal(model.instance$`add_contents`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # New description for the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("details", {
  # tests for the property `details` (object)
  # New details for the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`details`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # New name for the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("remove_contents", {
  # tests for the property `remove_contents` (array[CollectionItem])
  # List of items to remove from the collection. Items must match exactly to be removed. Items not found in the collection are ignored. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`remove_contents`, "EXPECTED_RESULT")
})

