# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject6")

model.instance <- InlineObject6$new()

test_that("es_query", {
  # tests for the property `es_query` (object)
  # Elasticsearch query

  # uncomment below to test the property 
  #expect_equal(model.instance$`es_query`, "EXPECTED_RESULT")
})

