# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CollectionOfCollectionsItem")

model.instance <- CollectionOfCollectionsItem$new()

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A UUID identifying the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # The version of the UUID identifying the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

