# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject3")

model.instance <- InlineObject3$new()

test_that("destination", {
  # tests for the property `destination` (character)
  # User-owned destination storage bucket.

  # uncomment below to test the property 
  #expect_equal(model.instance$`destination`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # An email address to send status updates to.

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

