# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2005")

model.instance <- InlineResponse2005$new()

test_that("collections", {
  # tests for the property `collections` (array[CollectionOfCollectionsItem])
  # A user&#39;s collection UUIDs and versions.

  # uncomment below to test the property 
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

