# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject5")

model.instance <- InlineObject5$new()

test_that("creator_uid", {
  # tests for the property `creator_uid` (integer)
  # User ID who is creating this file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`creator_uid`, "EXPECTED_RESULT")
})

test_that("source_url", {
  # tests for the property `source_url` (character)
  # Cloud bucket URL for source data.  Example is \&quot;s3://bucket_name/serious_dna.fa\&quot; .

  # uncomment below to test the property 
  #expect_equal(model.instance$`source_url`, "EXPECTED_RESULT")
})

