# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundleFile")

model.instance <- BundleFile$new()

test_that("indexed", {
  # tests for the property `indexed` (character)
  # True iff this file should be indexed.

  # uncomment below to test the property 
  #expect_equal(model.instance$`indexed`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the file. - Absolute paths (beginning with a slash) are not allowed. - Relative paths must not have unix shortcuts (i.e. \&quot;.\&quot;, \&quot;..\&quot;, \&quot;~/\&quot;) - No \&quot;\\\&quot; (back)slashes allowed.  e.g. \&quot;C:\\\\path\&quot; or \&quot;path\\file.json\&quot; - Only relative paths with \&quot;/\&quot; (forward)slashes allowed.  e.g. \&quot;path/file.json\&quot; or \&quot;file.json\&quot; - Please upload using \&quot;/\&quot; (forward)slashes, even if on Windows. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A RFC4122-compliant ID for the file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of file creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

