# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponseDefault6")

model.instance <- InlineResponseDefault6$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly.  The code &#x60;invalid_link&#x60; indicates that an item listed in the collection contents field of the input could not be resolved (either because the file, bundle, or collection does not exist on the replica specified, or because the JSON Pointer reference could not be resolved within the specified file). 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

