# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse4001")

model.instance <- InlineResponse4001$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly. The code &#x60;duplicate_filename&#x60; is returned when the bundle contains two files of the same name. The code &#x60;file_missing&#x60; is returned when the server cannot find one of the files requested to be included in the bundle. The code &#x60;illegal_version&#x60; is returned when version is not a DSS_VERSION format-compliant timestamp. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

