# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Bundle")

model.instance <- Bundle$new()

test_that("uuid", {
  # tests for the property `uuid` (character)
  # Bundle unique ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("versions", {
  # tests for the property `versions` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`versions`, "EXPECTED_RESULT")
})

