# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubscriptionsAttachments")

model.instance <- SubscriptionsAttachments$new()

test_that("expression", {
  # tests for the property `expression` (character)
  # The JMESPath expression to evaluate against the bundle metadata JSON document. That document is of the same structure as those returned by &#x60;POST /search&#x60; with &#x60;output_format: raw&#x60;. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`expression`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (object)
  # The type of the attachment. Currently only the &#x60;jmespath&#x60; type is supported.

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

