# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CollectionItem")

model.instance <- CollectionItem$new()

test_that("path", {
  # tests for the property `path` (character)
  # JSON Pointer indexing into the JSON contents of the file containing a metadata fragment. Required for links of type other than file, bundle, or collection. Ignored otherwise. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Type of link (file, bundle, collection, or a custom type for a metadata fragment).

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # Unique ID of the file, bundle, collection, or file containing a metadata fragment.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # DSS_VERSION format timestamp of the file, bundle, collection, or file containing a metadata fragment.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

