# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BundleVersion")

model.instance <- BundleVersion$new()

test_that("creator_uid", {
  # tests for the property `creator_uid` (integer)
  # User ID who created this bundle manifest.

  # uncomment below to test the property 
  #expect_equal(model.instance$`creator_uid`, "EXPECTED_RESULT")
})

test_that("files", {
  # tests for the property `files` (array[FileVersion])

  # uncomment below to test the property 
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # Bundle unique ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of bundle creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

