# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse400")

model.instance <- InlineResponse400$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly.  The code &#x60;illegal_arguments&#x60; is returned when required parameters are missing or parameters do not match the requirements in the specification.  The code &#x60;illegal_token&#x60; is returned when the token parameter cannot be understood.  The code &#x60;only_one_urltype&#x60; is returned when more than one url type (&#x60;directurls&#x60; and &#x60;presignedurls&#x60;) is requested. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

