# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2002")

model.instance <- InlineResponse2002$new()

test_that("manifest", {
  # tests for the property `manifest` (object)
  # The manifest stored in the DSS. It lists the files in the bundle, and metadata describing those files.

  # uncomment below to test the property 
  #expect_equal(model.instance$`manifest`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of bundle creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

