# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject2")

model.instance <- InlineObject2$new()

test_that("add_files", {
  # tests for the property `add_files` (array[BundleFile])
  # List of new files to add to the bundle. File names must be unique. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`add_files`, "EXPECTED_RESULT")
})

test_that("remove_files", {
  # tests for the property `remove_files` (array[BundleFile])
  # List of files to remove from the bundle. Files must match exactly to be removed. Files not found in the bundle are ignored. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`remove_files`, "EXPECTED_RESULT")
})

