# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20011")

model.instance <- InlineResponse20011$new()

test_that("subscription", {
  # tests for the property `subscription` (Subscription)

  # uncomment below to test the property 
  #expect_equal(model.instance$`subscription`, "EXPECTED_RESULT")
})

