# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EventsManifestEvents")

model.instance <- EventsManifestEvents$new()

test_that("event_id", {
  # tests for the property `event_id` (character)
  # The event identifier.

  # uncomment below to test the property 
  #expect_equal(model.instance$`event_id`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (integer)
  # The location of the event data in the journal, as 0-indexed byte offset.

  # uncomment below to test the property 
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)
  # The size of the event data in bytes

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # DSS_VERSION format timestamp of the event.

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

