# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test File")

model.instance <- File$new()

test_that("name", {
  # tests for the property `name` (character)
  # Filename (unique within a bundle)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("uuid", {
  # tests for the property `uuid` (character)
  # File unique ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("versions", {
  # tests for the property `versions` (array[character])
  # List of versions

  # uncomment below to test the property 
  #expect_equal(model.instance$`versions`, "EXPECTED_RESULT")
})

