# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2001")

model.instance <- InlineResponse2001$new()

test_that("bundle", {
  # tests for the property `bundle` (BundleVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`bundle`, "EXPECTED_RESULT")
})

