# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200")

model.instance <- InlineResponse200$new()

test_that("cause", {
  # tests for the property `cause` (character)
  # Human readable description of the error, returned for FAILED status only.

  # uncomment below to test the property 
  #expect_equal(model.instance$`cause`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Status of the checkout request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

