# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20010")

model.instance <- InlineResponse20010$new()

test_that("subscriptions", {
  # tests for the property `subscriptions` (array[Subscription])

  # uncomment below to test the property 
  #expect_equal(model.instance$`subscriptions`, "EXPECTED_RESULT")
})

