# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse4003")

model.instance <- InlineResponse4003$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # The code &#x60;illegal_version&#x60; is returned when version is not a DSS_VERSION format-compliant timestamp. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

