# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EventsManifest")

model.instance <- EventsManifest$new()

test_that("events", {
  # tests for the property `events` (array[EventsManifestEvents])
  # A list describing the event content of the journal.

  # uncomment below to test the property 
  #expect_equal(model.instance$`events`, "EXPECTED_RESULT")
})

test_that("from_date", {
  # tests for the property `from_date` (character)
  # DSS_VERSION format timestamp of the first event in the journal.

  # uncomment below to test the property 
  #expect_equal(model.instance$`from_date`, "EXPECTED_RESULT")
})

test_that("journal_id", {
  # tests for the property `journal_id` (character)
  # The event journal identifier.

  # uncomment below to test the property 
  #expect_equal(model.instance$`journal_id`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)
  # Size of the journal in bytes.

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("to_date", {
  # tests for the property `to_date` (character)
  # DSS_VERSION format timestamp of the last event in the journal.

  # uncomment below to test the property 
  #expect_equal(model.instance$`to_date`, "EXPECTED_RESULT")
})

