# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2011")

model.instance <- InlineResponse2011$new()

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A RFC4122-compliant ID for the subscription.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

