# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse4005")

model.instance <- InlineResponse4005$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly. The code &#x60;unknown_source_schema&#x60; is returned when the source_url of the file has an unsupported schema. The code &#x60;illegal_version&#x60; is returned when version is not a DSS_VERSION format-compliant timestamp. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

