# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2006")

model.instance <- InlineResponse2006$new()

test_that("collection", {
  # tests for the property `collection` (Collection)

  # uncomment below to test the property 
  #expect_equal(model.instance$`collection`, "EXPECTED_RESULT")
})

