# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Collection")

model.instance <- Collection$new()

test_that("contents", {
  # tests for the property `contents` (array[CollectionItem])
  # A list of objects describing links to files, bundles, other collections, and metadata fragments that are part of the collection. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`contents`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # A long description of the collection, formatted in Markdown.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("details", {
  # tests for the property `details` (object)
  # Supplementary JSON metadata for the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`details`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # A short name identifying the collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

