# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2007")

model.instance <- InlineResponse2007$new()

test_that("uuid", {
  # tests for the property `uuid` (character)
  # A RFC4122-compliant ID of this collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # New version of the updated collection.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

