# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2009")

model.instance <- InlineResponse2009$new()

test_that("version", {
  # tests for the property `version` (character)
  # Timestamp of file creation in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

