# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2004")

model.instance <- InlineResponse2004$new()

test_that("checkout_job_id", {
  # tests for the property `checkout_job_id` (character)
  # A RFC4122-compliant ID for the checkout job request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`checkout_job_id`, "EXPECTED_RESULT")
})

