# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject")

model.instance <- InlineObject$new()

test_that("creator_uid", {
  # tests for the property `creator_uid` (integer)
  # User ID who is creating this bundle.

  # uncomment below to test the property 
  #expect_equal(model.instance$`creator_uid`, "EXPECTED_RESULT")
})

test_that("files", {
  # tests for the property `files` (array[BundleFile])
  # This is a list of dictionaries describing each of the files. Each dictionary includes the fields: - The \&quot;uuid\&quot; of a file already previously uploaded with \&quot;PUT file/{uuid}\&quot;. - The \&quot;version\&quot; timestamp of the file. - The \&quot;name\&quot; of the file. This can be most anything, and is the name the file will have when downloaded. - The \&quot;indexed\&quot; field, which specifies whether a file should be indexed or not. Bundle manifests exceeding 20,000 files will not be included in the Elasticsearch index document. Example representing 2 files with dummy values: [{&#39;uuid&#39;: &#39;ce55fd51-7833-469b-be0b-5da88ebebfcd&#39;,   &#39;version&#39;: &#39;2017-06-16T193604.240704Z&#39;,   &#39;name&#39;: &#39;dinosaur_dna.fa&#39;,   &#39;indexed&#39;: False},  {&#39;uuid&#39;: &#39;ae55fd51-7833-469b-be0b-5da88ebebfca&#39;,   &#39;version&#39;: &#39;0303-04-23T193604.240704Z&#39;,   &#39;name&#39;: &#39;dragon_dna.fa&#39;,   &#39;indexed&#39;: False}] 

  # uncomment below to test the property 
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

