# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponseDefault4")

model.instance <- InlineResponseDefault4$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly.

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

