# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2008")

model.instance <- InlineResponse2008$new()

test_that("manifest", {
  # tests for the property `manifest` (EventsManifest)

  # uncomment below to test the property 
  #expect_equal(model.instance$`manifest`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # Location of the journal data.

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

