# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse4221")

model.instance <- InlineResponse4221$new()

test_that("Error", {
  # tests for the property `Error` (Error)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Error`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)
  # Machine-readable error code.  The types of return values should not be changed lightly. The code &#x60;missing_checksum&#x60; is returned when the file uploaded is missing a required checksum. The code &#x60;invalid_checksum&#x60; is returned when a checksum is provided but badly-formed.

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

