# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse20012")

model.instance <- InlineResponse20012$new()

test_that("timeDeleted", {
  # tests for the property `timeDeleted` (character)
  # Timestamp of query subscription deletion in DSS_VERSION format.

  # uncomment below to test the property 
  #expect_equal(model.instance$`timeDeleted`, "EXPECTED_RESULT")
})

