setGeneric("nextResults", function(x, ...) standardGeneric("nextResults"))
setGeneric('first_hit', function(x, ...) standardGeneric('first_hit'))
setGeneric('last_hit', function(x, ...) standardGeneric('last_hit'))
setGeneric('total_hits', function(x, ...) standardGeneric('total_hits'))
setGeneric('es_query', function(x, ...) standardGeneric('es_query'))
setGeneric('results', function(x, ...) standardGeneric('results'))
setGeneric('link', function(x, ...) standardGeneric('link'))
setGeneric('undoEsQuery', function(x, ...) standardGeneric('undoEsQuery'))
setGeneric('resetEsQuery', function(x, ...) standardGeneric('resetEsQuery'))
setGeneric('per_page', function(x, ...) standardGeneric('per_page'))

setGeneric('searchPost', function(x, ...) standardGeneric('searchPost'))
setGeneric('bundleGet', function(x, ...) standardGeneric('bundleGet'))
